[build]
  publish = "/"

# Form submissions
[forms]
  [forms.contact-form]
    name = "contact-form"

# Redirect to index for 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache control for CSS/JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"